<a href="https://colab.research.google.com/github/ALEKSGILLACERDA/comp-2/blob/main/exercicos_em_sala.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

## Problema. Redija um procedimento g(ls) que recebe uma lista de
## inteiros e retorna um booleano indicando se há algum número inteiro
## par na lista.  Por exemplo,
##
## g([1, 3, 1, 11]) --> False
## g([]) --> False
## g([1, 6]) --> True
##
## Eis como pensar no problema.  Defina um predicado is_even(i) que
## diz quando um número é par ou ímpar.  Em seguida, use-o para
## filtrar os que são pares.  Quando seu filtro retorna vazio, o que
## isso significa?  Responda à pergunta e termine seu procedimento g.

def g(ls):
  pass

## Problema. Considere a série
##
##    Sigma (-1)^n / (2n + 1) = 1 - 1/3 + 1/5 -  1/7 + 1/9 + ...
##
## de n = 0 até o infinito, cuja soma converge pra pi/4.  Redija um
## procedimento h(n) que dado um natural n, produza uma lista contendo
## os termos da série representados (cada um) por um objeto Fraction,
## ignorando-se o sinal do termo; por exemplo, se n = 3, seu
## procedimento produz
##
##   [Fraction(1,1), Fraction(1, 3), Fraction(1, 5)].

def h(n):
  pass

## Problema. Redija um procedimento j(fs) que consome a lista
## produzida por h(n) do problema anterior e produz outra colocando-se
## o sinal negativo em cada termo ímpar; por exemplo,
##
##    j([Fraction(1,1), Fraction(1, 3), Fraction(1, 5)])
##
## produz
##
##    j([Fraction(1,1), Fraction(-1, 3), Fraction(1, 5)]).

def j(fs):
  pass

## Problema. Redija um procedimento k(fs) que consome a lista
## produzida por j(fs) do problem anterior e produz um objeto Fraction
## que represente a soma.

def k(fs):
  pass

## Problema. Redija um procedimento f(it, e) que consome um iterável
## it qualquer (ou seja, uma string, uma lista, uma tupla, um
## dicionário et cetera) e um valor /e/ que pode pertencer ao iterável
## ou não.  Seu procedimento deve produzir a quantidade de vezes em
## que o elemento ocorre no iterável.  Por exemplo,
##
##  f("hello", "l") --> 2
##  f([], None) --> 0

def f(it, e):
  pass

## Problema. Uma máscara indica informação que pode ser mostrada ao
## usuário e informação que deve ser escondida, isto é, mascarada.
## Numa implementação do jogo da forca, usamos uma máscara pra indicar
## que posições da palavra secreta o jogador já acertou (e cujo
## conteúdo, portanto, deve ser mostrado ao jogador) e que posições
## devem continuar escondidas.  Cada vez que o jogador acerta uma
## letra da palavra oculta, a máscara é atualizada de forma a ficar
## com tracinhos nos lugares de letras que o jogador ainda não
## acertou; e mostrar, no seu devido lugar, as letras que ele já
## acertou. Por exemplo, se a palavra for “carta”, a máscara atual for
##
##                           - a - - a
##
## e o jogador escolher a letra "t", a máscara deve ser atualizada pra
##
##                           - a - t a
##
## Redija um procedimento chamado atualiza(sec, ls, let) que recebe
## como entrada uma string contendo a palavra secreta (por exemplo,
## sec = "carta"), uma lista cujos elementos sao os caracteres da
## máscara atual (por exemplo, ls = ["-","a","-","-","a"]) e uma
## string com a letra que ele acabou de escolher.  Seu procedimento
## deve produzir uma nova máscara, colocando a letra escolhida no seu
## devido lugar (caso esteja na palavra).  Se a letra não estiver na
## palavra, a nova máscara deve retornar sem modificações.

def mascara(sec):
  return list(map(lambda x: "-", sec))

def atualiza(sec, ls, let):
  def check(s, x):
    if s == let:
      return s
    else:
      return x
  return list(map(check, sec, ls))

## Problema. Redija um procedimento indice(M, x) que recebe uma matriz
## M e um inteiro x e retorna o índice da primeira linha de M que
## contém x.  O que definimos como matriz é uma lista de listas.  Por
## exemplo, a matriz identidade de dimensões 2x2 é [[1,0], [0,1]].
##
## Eis uma forma de pensar no problema: primeiro construa um
## procedimento p(M, x) que construi uma lista de tuplas contendo o
## índice, a linha da matrix e um booleano que diz se x está presente
## na linha da matriz ou não.  Dica: use enumerate(fs) pra obter
## índices que enumeram uma lista qualquer.  Experimente no seu shell:
## list(enumerate("abc")). Em seguida, filtre o resultado de p(M, x)
## pelas tuplas que possuem o booleano True.  Por fim, escreva um
## procedimento indice(M, x) que produz o índice da primeira
## ocorrência.

def indice(M, x):
  pass

def p(M, x):
  pass

def q(ts):
  pass

## Problema. Redija um procedimento r(M, k) que consome uma matriz M
## e um inteiro k e produza uma nova matriz que represente a
## multiplicação M*k.

def r(M, k):
  pass

## Problema. Redija uma procedimento s(M1, M2) que consome duas
## matrizes M1, M2 e produz a soma M1 + M2.

def s(M1, M2):
  pass

## Redija um procedimento flatten(ls) que consome uma lista como
## [["a"], ["b"], ["c"]] e produz uma lista ["a", "b", "c"], ou seja,
## seu procedimento achata uma lista que tinha ``um certo relevo''.
## Você consegue achatar uma lista pegando cada elemento dela e
## concatenando-a com a lista vazia.  Observe: [] + ["a"] = ["a"];
## depois ["a"] + ["b"] = ["a", "b"]; depois
##
##   ["a", "b"] + ["c"] = ["a", "b", "c"]
##
## como desejado.

def flatten(ls):
  return reduce(lambda x, y: x + y, ls, [])

## Problema. Use flatten(ls) e depois map() pra produzir o produto
## cartesiano de uma lista de strings.  Chame seu procedimento de
## cartesian(ns), sendo ns uma string de nomes.  Por exemplo,
##
##   cartesian(["Leo", "Sofia"]) -->
##          [("Leo", "Leo"), ("Leo", "Sofia"),
##           ("Sofia", "Leo"), ("Sofia", "Sofia")]

def cartesian(ns):
  return flatten(list(map(lambda n: list(map(lambda m: (n, m), ns)), ns)))

## Problema.  Relações de afinidades entre pessoas podem ser descritas
## através de dicionários.  Por exemplo, suponha que
##
## 1. Leo curtiu Sofia, Andrea e Bia;
## 2. Marcos curtiu Andrea e Bia;
## 3. Sofia curtiu Leo;
## 4. Alex curtiu Andrea e Marcos;
## 5. Andrea curtiu Marcos;
## 6. Bia curtiu Sofia.
##
## Podemos representar essa suposição usando o dicionário

def afinidades():
  return {
    'Leo': ['Sofia', 'Andrea', 'Bia'],
    'Marcos': ['Andrea', 'Bia'],
    'Sofia': ['Leo'],
    'Alex': ['Andrea', 'Marcos'],
    'Andrea': ['Marcos'],
    'Bia':['Sofia', 'Jack'],
    'Jack': []
  }

## Redija um procedimento match_with_duplicates(d) que consome um
## dicionário d como produzido por afinidades() e produz uma lista de
## tuplas (p, q) sempre que p tem afinidade mútua com q.  Note que se
## p tem afinidade com q, então seu procedimento vai produzir os
## duplicatas (p, q) e (q, p).  Por exemplo, Leo tem afinidade mútua
## com Sofia porque Leo gosta de Sofia e vice-versa; então ambos
##
##   ("Leo", "Sofia") e ("Sofia", "Leo")
##
## são parte da resposta relativa ao dicionário afinidades() acima.
##
## Use cartesian(ns) pra gerar todos as afinidades possíveis e então
## use um filtro com um detector que indica quando um par tem
## afinidade mútua.  Certifique-se se inserir os duplicatas.

def matches_with_duplicates(d):
  def mutual(pair):
    left, right = pair
    return left in d[right] and right in d[left]
  return list(filter(mutual, cartesian(d.keys())))

## Problema.  Use uma redução pra remover os duplicatas gerados pelo
## problema anterior.  Note que seu operador de redução não é
## comutativo; logo, o primeiro argumento do seu operador precisa ser
## o acumulador (porque essa é a ordem imposta por functool.reduce).

def matches(ls):
  def addcheck(acc, pair):
    left, right = pair
    if (right, left) not in acc:
      return acc + [(left, right)]
    else:
      return acc
  return list(reduce(addcheck, ls, []))

In [17]:
import functools as f

def g(ls):
  return f.reduce(lambda x, y: x or ( y % 2 == 0), ls, False)

g([1,3,5])



False

In [30]:
#outra forma de resolver o problema acima

def is_even(ls):
  return list(map(lambda x: x%2 == 0, ls))


def g(ls):
  even = is_even(ls)
  return any(even)

g([1])


False

In [33]:
from fractions import Fraction
from functools import reduce
#print(frac)

def numerador(n):
  numerador = (-1)**n
  return numerador

def denominador(n):
  denominador = (2*n + 1)
  return denominador



def h(n):
  return [Fraction(numerador(i), denominador(i)) for i in range(n +1)]



def f(n):
    fracoes = h(n)
    # muito dificil usar map nesse
    transformados = list(map(
        lambda item: -item[1] if item[0] % 2 != 0 else item[1],
        enumerate(fracoes)
    ))
    return transformados

resultado = f(5)
print(resultado)

def  k(n):
  lista = f(n)
  soma = reduce(lambda x, y: x+y, lista)
  print(soma)

k(5)

[Fraction(1, 1), Fraction(1, 3), Fraction(1, 5), Fraction(1, 7), Fraction(1, 9), Fraction(1, 11)]
6508/3465


In [38]:
# Problema. Redija um procedimento f(it, e) que consome um iterável
## it qualquer (ou seja, uma string, uma lista, uma tupla, um
## dicionário et cetera) e um valor /e/ que pode pertencer ao iterável
## ou não.  Seu procedimento deve produzir a quantidade de vezes em
# que o elemento ocorre no iterável.


def f(it, e):
  lista_nova = list(filter(lambda x: x == e, it ))
  print(len(lista_nova))
f([1, 2, 3, 4], 4)



1


In [42]:
## Redija um procedimento chamado atualiza(sec, ls, let) que recebe
## como entrada uma string contendo a palavra secreta (por exemplo,
## sec = "carta"), uma lista cujos elementos sao os caracteres da
## máscara atual (por exemplo, ls = ["-","a","-","-","a"]) e uma
## string com a letra que ele acabou de escolher.  Seu procedimento
## deve produzir uma nova máscara, colocando a letra escolhida no seu
## devido lugar (caso esteja na palavra).  Se a letra não estiver na
## palavra, a nova máscara deve retornar sem modificações.

def secreto(sec):
    return list(map(lambda x: "-", sec))

def forca(ls, let, sec ):
  #muito dificil
    nova_mascara = list(map(lambda i: let if sec[i] == let else ls[i], range(len(sec))))
    return nova_mascara

sec = "caramba"
ls = secreto(sec)
print(ls)

ls = forca(ls, "a", sec)
print(ls)



['-', '-', '-', '-', '-', '-', '-']
['-', 'a', '-', 'a', '-', '-', 'a']


In [44]:
import numpy as np

def r(M, k):
  matriz_produto = M*k
  print(M)
  print(matriz_produto)
  pass
r(np.random.randint(1, 5, size=(3, 3)), 8)

[[1 2 3]
 [4 4 2]
 [2 3 2]]
[[ 8 16 24]
 [32 32 16]
 [16 24 16]]


In [46]:
## Redija um procedimento flatten(ls) que consome uma lista como
## [["a"], ["b"], ["c"]] e produz uma lista ["a", "b", "c"], ou seja,
## seu procedimento achata uma lista que tinha ``um certo relevo''.
## Você consegue achatar uma lista pegando cada elemento dela e
## concatenando-a com a lista vazia.  Observe: [] + ["a"] = ["a"];
## depois ["a"] + ["b"] = ["a", "b"]; depois
##
##   ["a", "b"] + ["c"] = ["a", "b", "c"]

def flatten(ls):
  return reduce(lambda x, y: x + y, ls, [])

flatten([["a"], ["b"], ["c"]])



['a', 'b', 'c']